In [92]:
import pandas as pd

In [93]:
pd.read_csv("https://raw.githubusercontent.com/sojog/ML-NLP-DP-Bittnet-Iulie-2026/refs/heads/main/Ziua3/Datasets/clwin.csv")

    id      country           team  trophies
0    0      England      Liverpool       6.0
1    1        Spain      Barcelona       5.0
2    2      England     Man United       3.0
3    3        Italy          Inter       3.0
4    4      England        Chelsea       2.0
5    5      England        Chelsea       2.0
6    6      England   Nottm Forest       2.0
7    7     Portugal        Benfica       2.0
8    8        Italy       Juventus       2.0
9    9     Portugal       FC Porto       2.0
10  10      England       Man City       1.0
11  11      Germany       Dortmund       1.0
12  12  Netherlands      Feyenoord       1.0
13  13       France      Marseille       1.0
14  14      England    Aston Villa       1.0
15  15      Germany        Hamburg       1.0
16  16       Serbia  Crvena zvezda       1.0
17  17      Romania           FCSB       NaN
18  18  Netherlands            PSV       1.0
19  19     Scotland         Celtic       1.0

# Citirea indexului fiind prima coloana

In [94]:
# 1. Importați fișierul CSV folosind Pandas și afișați primele 5 rânduri. 
df = pd.read_csv("Datasets/clwin.csv", index_col=0)

In [95]:
df = pd.read_csv("Datasets/clwin.csv", index_col="id")
df

        country           team  trophies
id
0       England      Liverpool       6.0
1         Spain      Barcelona       5.0
2       England     Man United       3.0
3         Italy          Inter       3.0
4       England        Chelsea       2.0
5       England        Chelsea       2.0
6       England   Nottm Forest       2.0
7      Portugal        Benfica       2.0
8         Italy       Juventus       2.0
9      Portugal       FC Porto       2.0
10      England       Man City       1.0
11      Germany       Dortmund       1.0
12  Netherlands      Feyenoord       1.0
13       France      Marseille       1.0
14      England    Aston Villa       1.0
15      Germany        Hamburg       1.0
16       Serbia  Crvena zvezda       1.0
17      Romania           FCSB       NaN
18  Netherlands            PSV       1.0
19     Scotland         Celtic       1.0

In [96]:
# 2. Afișați tipurile de date ale fiecărei coloane. 
df.dtypes

country      object
team         object
trophies    float64
dtype: object

In [97]:
# 3. Obțineți statisticile rezumate ale coloanelor numerice din date.
df.describe()

        trophies
count  19.000000
mean    2.000000
std     1.414214
min     1.000000
25%     1.000000
50%     2.000000
75%     2.000000
max     6.000000

In [98]:
# 4. Verificați dacă există valori lipsă în setul de date. 
df.isna().sum()

country     0
team        0
trophies    1
dtype: int64

In [99]:
df[ df["trophies"].isna()]

    country  team  trophies
id
17  Romania  FCSB       NaN

In [100]:
# 5. Numărați câte echipe se află în total
df.count()

country     20
team        20
trophies    19
dtype: int64

In [101]:
# 6. Selectați și afișați coloanele „echipă” și „trofee”. 
df[["team", "trophies"]]

             team  trophies
id
0       Liverpool       6.0
1       Barcelona       5.0
2      Man United       3.0
3           Inter       3.0
4         Chelsea       2.0
5         Chelsea       2.0
6    Nottm Forest       2.0
7         Benfica       2.0
8        Juventus       2.0
9        FC Porto       2.0
10       Man City       1.0
11       Dortmund       1.0
12      Feyenoord       1.0
13      Marseille       1.0
14    Aston Villa       1.0
15        Hamburg       1.0
16  Crvena zvezda       1.0
17           FCSB       NaN
18            PSV       1.0
19         Celtic       1.0

In [102]:
df.drop_duplicates()

        country           team  trophies
id
0       England      Liverpool       6.0
1         Spain      Barcelona       5.0
2       England     Man United       3.0
3         Italy          Inter       3.0
4       England        Chelsea       2.0
6       England   Nottm Forest       2.0
7      Portugal        Benfica       2.0
8         Italy       Juventus       2.0
9      Portugal       FC Porto       2.0
10      England       Man City       1.0
11      Germany       Dortmund       1.0
12  Netherlands      Feyenoord       1.0
13       France      Marseille       1.0
14      England    Aston Villa       1.0
15      Germany        Hamburg       1.0
16       Serbia  Crvena zvezda       1.0
17      Romania           FCSB       NaN
18  Netherlands            PSV       1.0
19     Scotland         Celtic       1.0

In [103]:
# 7. Selectați rândurile în care țara este „Anglia”. 
df[df["country"] == "England"]

    country          team  trophies
id
0   England     Liverpool       6.0
2   England    Man United       3.0
4   England       Chelsea       2.0
5   England       Chelsea       2.0
6   England  Nottm Forest       2.0
10  England      Man City       1.0
14  England   Aston Villa       1.0

In [104]:
# 8. Afișează rândurile în care „trofeele” sunt mai mari decât 2.

df [df["trophies"] > 2]

    country        team  trophies
id
0   England   Liverpool       6.0
1     Spain   Barcelona       5.0
2   England  Man United       3.0
3     Italy       Inter       3.0

In [105]:
# 9. Accesați coloanele „echipă” și „țară” pentru primele 10 rânduri. 

df.drop("trophies", axis=1).head(10)

     country          team
id
0    England     Liverpool
1      Spain     Barcelona
2    England    Man United
3      Italy         Inter
4    England       Chelsea
5    England       Chelsea
6    England  Nottm Forest
7   Portugal       Benfica
8      Italy      Juventus
9   Portugal      FC Porto

In [106]:
# 10. Selectați ultimele 5 rânduri ale DataFrame. 
df.tail()

        country           team  trophies
id
15      Germany        Hamburg       1.0
16       Serbia  Crvena zvezda       1.0
17      Romania           FCSB       NaN
18  Netherlands            PSV       1.0
19     Scotland         Celtic       1.0

In [107]:


# 11. Filtrați echipele din „Spania” și afișați-le datele.

df[df["country"].isin(["Spain"])]

   country       team  trophies
id
1    Spain  Barcelona       5.0

In [108]:
# 12. Găsiți toate echipele care au câștigat exact 2 trofee. 
df[df["trophies"] == 2]

     country          team  trophies
id
4    England       Chelsea       2.0
5    England       Chelsea       2.0
6    England  Nottm Forest       2.0
7   Portugal       Benfica       2.0
8      Italy      Juventus       2.0
9   Portugal      FC Porto       2.0

In [109]:
df = df.drop_duplicates().reset_index(drop=True)
df

        country           team  trophies
0       England      Liverpool       6.0
1         Spain      Barcelona       5.0
2       England     Man United       3.0
3         Italy          Inter       3.0
4       England        Chelsea       2.0
5       England   Nottm Forest       2.0
6      Portugal        Benfica       2.0
7         Italy       Juventus       2.0
8      Portugal       FC Porto       2.0
9       England       Man City       1.0
10      Germany       Dortmund       1.0
11  Netherlands      Feyenoord       1.0
12       France      Marseille       1.0
13      England    Aston Villa       1.0
14      Germany        Hamburg       1.0
15       Serbia  Crvena zvezda       1.0
16      Romania           FCSB       NaN
17  Netherlands            PSV       1.0
18     Scotland         Celtic       1.0

In [110]:
# 13. Filtrați echipele în care țara este fie „Anglia”, fie „Italia”.
df[df["country"].isin(["Spain", "Italy"])]

  country       team  trophies
1   Spain  Barcelona       5.0
3   Italy      Inter       3.0
7   Italy   Juventus       2.0

In [111]:
# 13. Filtrați echipele în care țara este fie „Anglia”, fie „Italia”.

df[(df["country"] == "Spain") | (df["country"] == "Italy") ]

  country       team  trophies
1   Spain  Barcelona       5.0
3   Italy      Inter       3.0
7   Italy   Juventus       2.0

In [112]:
in_spania = df["country"] == "Spain"
in_italia = df["country"] == "Italy"
df[ in_spania | in_italia ]

  country       team  trophies
1   Spain  Barcelona       5.0
3   Italy      Inter       3.0
7   Italy   Juventus       2.0

In [113]:
# 14. Selectează echipele care au mai mult de 2 dar mai puțin de 7 trofee.
df[(df["trophies"] > 2) & (df["trophies"] < 7)]

   country        team  trophies
0  England   Liverpool       6.0
1    Spain   Barcelona       5.0
2  England  Man United       3.0
3    Italy       Inter       3.0

In [114]:
df[ df["trophies"].isin(range(3, 8))]

   country        team  trophies
0  England   Liverpool       6.0
1    Spain   Barcelona       5.0
2  England  Man United       3.0
3    Italy       Inter       3.0

In [115]:
# 15. Concatenati un nou DataFrame cu Manchester City și PSG cu 1 trofeu.

city_psg = pd.DataFrame({ "country" : ["England", "France"],	"team":["Man City", "PSG"], "trophies":[1, 2] })
city_psg

   country      team  trophies
0  England  Man City         1
1   France       PSG         2

In [116]:
pd.DataFrame([["Spain", "Real Madrid", 15], ["Italy", "Milan", 7], ["Germany", "Bayern", 6]])

         0            1   2
0    Spain  Real Madrid  15
1    Italy        Milan   7
2  Germany       Bayern   6

In [117]:
big_clubs = pd.DataFrame([["Spain", "Real Madrid", 15], ["Italy", "Milan", 7], ["Germany", "Bayern", 6]], columns=df.keys())
big_clubs

   country         team  trophies
0    Spain  Real Madrid        15
1    Italy        Milan         7
2  Germany       Bayern         6

In [118]:
df = pd.concat([df, city_psg, big_clubs], axis=0)
df

        country           team  trophies
0       England      Liverpool       6.0
1         Spain      Barcelona       5.0
2       England     Man United       3.0
3         Italy          Inter       3.0
4       England        Chelsea       2.0
5       England   Nottm Forest       2.0
6      Portugal        Benfica       2.0
7         Italy       Juventus       2.0
8      Portugal       FC Porto       2.0
9       England       Man City       1.0
10      Germany       Dortmund       1.0
11  Netherlands      Feyenoord       1.0
12       France      Marseille       1.0
13      England    Aston Villa       1.0
14      Germany        Hamburg       1.0
15       Serbia  Crvena zvezda       1.0
16      Romania           FCSB       NaN
17  Netherlands            PSV       1.0
18     Scotland         Celtic       1.0
0       England       Man City       1.0
1        France            PSG       2.0
0         Spain    Real Madrid      15.0
1         Italy          Milan       7.0
2       Germany         Bayern       6.0

In [123]:
# 17. Editați intrarea FCSB în Steaua și nr de trofee aferent.
df.loc[ df["team"] == "FCSB"]

    country  team  trophies
23  Romania  FCSB       NaN

In [124]:
df.loc[ df["team"] == "FCSB", "team"]

23    FCSB
Name: team, dtype: object

In [126]:
df.loc[ df["team"] == "FCSB", "team"] = "Steaua"
df

        country           team  trophies
0         Spain    Real Madrid      15.0
1         Italy          Milan       7.0
2       England      Liverpool       6.0
3       Germany         Bayern       6.0
4         Spain      Barcelona       5.0
5       England     Man United       3.0
6         Italy          Inter       3.0
7       England        Chelsea       2.0
8       England   Nottm Forest       2.0
9        France            PSG       2.0
10        Italy       Juventus       2.0
11     Portugal        Benfica       2.0
12     Portugal       FC Porto       2.0
13      England       Man City       1.0
14      England    Aston Villa       1.0
15      England       Man City       1.0
16       France      Marseille       1.0
17      Germany       Dortmund       1.0
18      Germany        Hamburg       1.0
19  Netherlands      Feyenoord       1.0
20  Netherlands            PSV       1.0
21     Scotland         Celtic       1.0
22       Serbia  Crvena zvezda       1.0
23      Romania         Steaua       NaN

In [128]:
df.loc[ df["team"] == "Steaua", ["team", "trophies"]] = ["Steaua", 1]
df.tail(2)

    country           team  trophies
22   Serbia  Crvena zvezda       1.0
23  Romania         Steaua       1.0

In [130]:
# 18. Adaugati la final Ajax Amsterdam cu 4 trofee
df.loc[len(df) - 1]

country     Romania
team         Steaua
trophies        1.0
Name: 23, dtype: object

In [131]:
df.loc[len(df)] = ["Netherlands", "Ajax", 4]

In [132]:
df

        country           team  trophies
0         Spain    Real Madrid      15.0
1         Italy          Milan       7.0
2       England      Liverpool       6.0
3       Germany         Bayern       6.0
4         Spain      Barcelona       5.0
5       England     Man United       3.0
6         Italy          Inter       3.0
7       England        Chelsea       2.0
8       England   Nottm Forest       2.0
9        France            PSG       2.0
10        Italy       Juventus       2.0
11     Portugal        Benfica       2.0
12     Portugal       FC Porto       2.0
13      England       Man City       1.0
14      England    Aston Villa       1.0
15      England       Man City       1.0
16       France      Marseille       1.0
17      Germany       Dortmund       1.0
18      Germany        Hamburg       1.0
19  Netherlands      Feyenoord       1.0
20  Netherlands            PSV       1.0
21     Scotland         Celtic       1.0
22       Serbia  Crvena zvezda       1.0
23      Romania         Steaua       1.0
24  Netherlands           Ajax       4.0

In [133]:


# 19. Sortati in funcție de trofeele câștigate descrescător și țară, reindexati tot df si salvati-l intr-un nou csv 
df = df.sort_values(["trophies", "country"], ascending=[False, True]).reset_index(drop=True)
df

        country           team  trophies
0         Spain    Real Madrid      15.0
1         Italy          Milan       7.0
2       England      Liverpool       6.0
3       Germany         Bayern       6.0
4         Spain      Barcelona       5.0
5   Netherlands           Ajax       4.0
6       England     Man United       3.0
7         Italy          Inter       3.0
8       England        Chelsea       2.0
9       England   Nottm Forest       2.0
10       France            PSG       2.0
11        Italy       Juventus       2.0
12     Portugal        Benfica       2.0
13     Portugal       FC Porto       2.0
14      England       Man City       1.0
15      England    Aston Villa       1.0
16      England       Man City       1.0
17       France      Marseille       1.0
18      Germany       Dortmund       1.0
19      Germany        Hamburg       1.0
20  Netherlands      Feyenoord       1.0
21  Netherlands            PSV       1.0
22      Romania         Steaua       1.0
23     Scotland         Celtic       1.0
24       Serbia  Crvena zvezda       1.0