In [1]:
import pandas as pd

In [2]:
pd.read_csv("https://raw.githubusercontent.com/sojog/ML-NLP-DP-Bittnet-Iulie-2026/refs/heads/main/Ziua3/Datasets/clwin.csv")

    id      country           team  trophies
0    0      England      Liverpool       6.0
1    1        Spain      Barcelona       5.0
2    2      England     Man United       3.0
3    3        Italy          Inter       3.0
4    4      England        Chelsea       2.0
5    5      England        Chelsea       2.0
6    6      England   Nottm Forest       2.0
7    7     Portugal        Benfica       2.0
8    8        Italy       Juventus       2.0
9    9     Portugal       FC Porto       2.0
10  10      England       Man City       1.0
11  11      Germany       Dortmund       1.0
12  12  Netherlands      Feyenoord       1.0
13  13       France      Marseille       1.0
14  14      England    Aston Villa       1.0
15  15      Germany        Hamburg       1.0
16  16       Serbia  Crvena zvezda       1.0
17  17      Romania           FCSB       NaN
18  18  Netherlands            PSV       1.0
19  19     Scotland         Celtic       1.0

# Citirea indexului fiind prima coloana

In [ ]:
# 1. Importați fișierul CSV folosind Pandas și afișați primele 5 rânduri. 
df = pd.read_csv("Datasets/clwin.csv", index_col=0)

In [7]:
df = pd.read_csv("Datasets/clwin.csv", index_col="id")
df

        country           team  trophies
id
0       England      Liverpool       6.0
1         Spain      Barcelona       5.0
2       England     Man United       3.0
3         Italy          Inter       3.0
4       England        Chelsea       2.0
5       England        Chelsea       2.0
6       England   Nottm Forest       2.0
7      Portugal        Benfica       2.0
8         Italy       Juventus       2.0
9      Portugal       FC Porto       2.0
10      England       Man City       1.0
11      Germany       Dortmund       1.0
12  Netherlands      Feyenoord       1.0
13       France      Marseille       1.0
14      England    Aston Villa       1.0
15      Germany        Hamburg       1.0
16       Serbia  Crvena zvezda       1.0
17      Romania           FCSB       NaN
18  Netherlands            PSV       1.0
19     Scotland         Celtic       1.0

In [9]:
# 2. Afișați tipurile de date ale fiecărei coloane. 
df.dtypes

country      object
team         object
trophies    float64
dtype: object

In [10]:
# 3. Obțineți statisticile rezumate ale coloanelor numerice din date.
df.describe()

        trophies
count  19.000000
mean    2.000000
std     1.414214
min     1.000000
25%     1.000000
50%     2.000000
75%     2.000000
max     6.000000

In [12]:
# 4. Verificați dacă există valori lipsă în setul de date. 
df.isna().sum()

country     0
team        0
trophies    1
dtype: int64

In [17]:
df[ df["trophies"].isna()]

    country  team  trophies
id
17  Romania  FCSB       NaN

In [18]:
# 5. Numărați câte echipe se află în total
df.count()

country     20
team        20
trophies    19
dtype: int64

In [19]:
# 6. Selectați și afișați coloanele „echipă” și „trofee”. 
df[["team", "trophies"]]

             team  trophies
id
0       Liverpool       6.0
1       Barcelona       5.0
2      Man United       3.0
3           Inter       3.0
4         Chelsea       2.0
5         Chelsea       2.0
6    Nottm Forest       2.0
7         Benfica       2.0
8        Juventus       2.0
9        FC Porto       2.0
10       Man City       1.0
11       Dortmund       1.0
12      Feyenoord       1.0
13      Marseille       1.0
14    Aston Villa       1.0
15        Hamburg       1.0
16  Crvena zvezda       1.0
17           FCSB       NaN
18            PSV       1.0
19         Celtic       1.0

In [20]:
df.drop_duplicates()

        country           team  trophies
id
0       England      Liverpool       6.0
1         Spain      Barcelona       5.0
2       England     Man United       3.0
3         Italy          Inter       3.0
4       England        Chelsea       2.0
6       England   Nottm Forest       2.0
7      Portugal        Benfica       2.0
8         Italy       Juventus       2.0
9      Portugal       FC Porto       2.0
10      England       Man City       1.0
11      Germany       Dortmund       1.0
12  Netherlands      Feyenoord       1.0
13       France      Marseille       1.0
14      England    Aston Villa       1.0
15      Germany        Hamburg       1.0
16       Serbia  Crvena zvezda       1.0
17      Romania           FCSB       NaN
18  Netherlands            PSV       1.0
19     Scotland         Celtic       1.0

In [21]:
# 7. Selectați rândurile în care țara este „Anglia”. 
df[df["country"] == "England"]

    country          team  trophies
id
0   England     Liverpool       6.0
2   England    Man United       3.0
4   England       Chelsea       2.0
5   England       Chelsea       2.0
6   England  Nottm Forest       2.0
10  England      Man City       1.0
14  England   Aston Villa       1.0

In [22]:
# 8. Afișează rândurile în care „trofeele” sunt mai mari decât 2.

df [df["trophies"] > 2]

    country        team  trophies
id
0   England   Liverpool       6.0
1     Spain   Barcelona       5.0
2   England  Man United       3.0
3     Italy       Inter       3.0

In [24]:
# 9. Accesați coloanele „echipă” și „țară” pentru primele 10 rânduri. 

df.drop("trophies", axis=1).head(10)

     country          team
id
0    England     Liverpool
1      Spain     Barcelona
2    England    Man United
3      Italy         Inter
4    England       Chelsea
5    England       Chelsea
6    England  Nottm Forest
7   Portugal       Benfica
8      Italy      Juventus
9   Portugal      FC Porto

In [25]:
# 10. Selectați ultimele 5 rânduri ale DataFrame. 
df.tail()

        country           team  trophies
id
15      Germany        Hamburg       1.0
16       Serbia  Crvena zvezda       1.0
17      Romania           FCSB       NaN
18  Netherlands            PSV       1.0
19     Scotland         Celtic       1.0

In [26]:


# 11. Filtrați echipele din „Spania” și afișați-le datele.

df[df["country"].isin(["Spain", "Italy"])]

   country       team  trophies
id
1    Spain  Barcelona       5.0
3    Italy      Inter       3.0
8    Italy   Juventus       2.0