In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("reviews.csv")
df

,review_uuid,review
0,bd649b56-653e-47b6-82a4-22ed7d6631d3,very bad
1,53c64956-156f-4ad1-9bb6-85f95d40c198,very good
2,d56c2d26-296f-4e6e-b9f9-516d08f78cad,waste product dont buy
3,7d2f7a42-a49e-474e-b2bd-4ca7159c4017,nice battery and fast charging
4,1717eae1-06f1-45bc-826b-35eb2fd3cc5f,product works great large steel jar was little...
...,...,...
2995,d2d936b5-5730-44b5-b0d8-81b811d427ed,very bad
2996,154a6ac7-69a0-4d9a-9587-07dbf6113fb2,i have received the worst product from the sel...
2997,ac610f15-7b2d-4610-b8cc-57643860c71e,quality of sole material is not good as well a...
2998,75bd4a53-ff9a-47ff-abaa-8a17c71575de,after using 4 to 5 days ice cream is melting
2999,499a943e-ac2d-46c9-a2c0-ab77e2425bf2,avg product cordlength is small and cooling sy...

In [4]:
# 1. Citiți fișierul într-un DataFrame. Afișați nr de. rânduri și coloane Verificați nr de valorile lipsă pe fiecare coloană. 
df.shape

(3000, 2)

In [5]:
df.isna().sum()

review_uuid    0
review         0
dtype: int64

In [7]:
# 2. Calculați lungimea medie a recenziilor în număr de cuvinte (creează o coloană auxiliară review_length).

df["review_length"] = df["review"].str.split()
df

,review_uuid,review,review_length
0,bd649b56-653e-47b6-82a4-22ed7d6631d3,very bad,"[very, bad]"
1,53c64956-156f-4ad1-9bb6-85f95d40c198,very good,"[very, good]"
2,d56c2d26-296f-4e6e-b9f9-516d08f78cad,waste product dont buy,"[waste, product, dont, buy]"
3,7d2f7a42-a49e-474e-b2bd-4ca7159c4017,nice battery and fast charging,"[nice, battery, and, fast, charging]"
4,1717eae1-06f1-45bc-826b-35eb2fd3cc5f,product works great large steel jar was little...,"[product, works, great, large, steel, jar, was..."
...,...,...,...
2995,d2d936b5-5730-44b5-b0d8-81b811d427ed,very bad,"[very, bad]"
2996,154a6ac7-69a0-4d9a-9587-07dbf6113fb2,i have received the worst product from the sel...,"[i, have, received, the, worst, product, from,..."
2997,ac610f15-7b2d-4610-b8cc-57643860c71e,quality of sole material is not good as well a...,"[quality, of, sole, material, is, not, good, a..."
2998,75bd4a53-ff9a-47ff-abaa-8a17c71575de,after using 4 to 5 days ice cream is melting,"[after, using, 4, to, 5, days, ice, cream, is,..."
2999,499a943e-ac2d-46c9-a2c0-ab77e2425bf2,avg product cordlength is small and cooling sy...,"[avg, product, cordlength, is, small, and, coo..."

In [9]:
'   TEXT  ALT TEXT  '.strip()

'TEXT  ALT TEXT'

In [10]:
'   TEXT  ALT TEXT  '.rstrip()

'   TEXT  ALT TEXT'

In [11]:
'   TEXT  ALT TEXT  '.lstrip()

'TEXT  ALT TEXT  '

In [12]:
df["review_length"] = df["review"].apply(lambda x: len(x.strip().split()))
df

,review_uuid,review,review_length
0,bd649b56-653e-47b6-82a4-22ed7d6631d3,very bad,2
1,53c64956-156f-4ad1-9bb6-85f95d40c198,very good,2
2,d56c2d26-296f-4e6e-b9f9-516d08f78cad,waste product dont buy,4
3,7d2f7a42-a49e-474e-b2bd-4ca7159c4017,nice battery and fast charging,5
4,1717eae1-06f1-45bc-826b-35eb2fd3cc5f,product works great large steel jar was little...,56
...,...,...,...
2995,d2d936b5-5730-44b5-b0d8-81b811d427ed,very bad,2
2996,154a6ac7-69a0-4d9a-9587-07dbf6113fb2,i have received the worst product from the sel...,29
2997,ac610f15-7b2d-4610-b8cc-57643860c71e,quality of sole material is not good as well a...,13
2998,75bd4a53-ff9a-47ff-abaa-8a17c71575de,after using 4 to 5 days ice cream is melting,10
2999,499a943e-ac2d-46c9-a2c0-ab77e2425bf2,avg product cordlength is small and cooling sy...,15

In [16]:
# 3. Standardizează coloana review la lowercase și fără spații stângă dreapta textului
df["review"] = df["review"].str.lower().str.strip()
df

,review_uuid,review,review_length
0,bd649b56-653e-47b6-82a4-22ed7d6631d3,very bad,2
1,53c64956-156f-4ad1-9bb6-85f95d40c198,very good,2
2,d56c2d26-296f-4e6e-b9f9-516d08f78cad,waste product dont buy,4
3,7d2f7a42-a49e-474e-b2bd-4ca7159c4017,nice battery and fast charging,5
4,1717eae1-06f1-45bc-826b-35eb2fd3cc5f,product works great large steel jar was little...,56
...,...,...,...
2995,d2d936b5-5730-44b5-b0d8-81b811d427ed,very bad,2
2996,154a6ac7-69a0-4d9a-9587-07dbf6113fb2,i have received the worst product from the sel...,29
2997,ac610f15-7b2d-4610-b8cc-57643860c71e,quality of sole material is not good as well a...,13
2998,75bd4a53-ff9a-47ff-abaa-8a17c71575de,after using 4 to 5 days ice cream is melting,10
2999,499a943e-ac2d-46c9-a2c0-ab77e2425bf2,avg product cordlength is small and cooling sy...,15

In [ ]:
# 4. Definește două liste:
#    - positive_words: ex. great, excellent, amazing, love, perfect, good, fantastic, happy, recommend
#    - negative_words: ex. bad, terrible, worst, broken, poor, disappointed, awful, hate, slow

# Crează o funcție care va mapa review-urile la 2 categorii: pozitive sau negative după regula
#  - dacă pos_hits >= neg_hits → "positive", altfel "negative"

In [18]:
positive_words =  "great, excellent, amazing, love, perfect, good, fantastic, happy, recommend".split(", ")
negative_words = "bad, terrible, worst, broken, poor, disappointed, awful, hate, slow".split(", ")
print(positive_words, negative_words)

['great', 'excellent', 'amazing', 'love', 'perfect', 'good', 'fantastic', 'happy', 'recommend'] ['bad', 'terrible', 'worst', 'broken', 'poor', 'disappointed', 'awful', 'hate', 'slow']

In [19]:
def eticheteaza(text:str):
    cuvinte = text.strip().split()
    pos_hits = sum( 1 for cuv in cuvinte if cuv in positive_words)
    neg_hits = sum( 1 for cuv in cuvinte if cuv in negative_words)
    return "positive" if pos_hits >= neg_hits else "negative"

In [20]:
eticheteaza(df.review[0])

'negative'

In [21]:
df["sentiment"] = df["review"].apply(eticheteaza)
df

,review_uuid,review,review_length,sentiment
0,bd649b56-653e-47b6-82a4-22ed7d6631d3,very bad,2,negative
1,53c64956-156f-4ad1-9bb6-85f95d40c198,very good,2,positive
2,d56c2d26-296f-4e6e-b9f9-516d08f78cad,waste product dont buy,4,positive
3,7d2f7a42-a49e-474e-b2bd-4ca7159c4017,nice battery and fast charging,5,positive
4,1717eae1-06f1-45bc-826b-35eb2fd3cc5f,product works great large steel jar was little...,56,positive
...,...,...,...,...
2995,d2d936b5-5730-44b5-b0d8-81b811d427ed,very bad,2,negative
2996,154a6ac7-69a0-4d9a-9587-07dbf6113fb2,i have received the worst product from the sel...,29,negative
2997,ac610f15-7b2d-4610-b8cc-57643860c71e,quality of sole material is not good as well a...,13,positive
2998,75bd4a53-ff9a-47ff-abaa-8a17c71575de,after using 4 to 5 days ice cream is melting,10,positive
2999,499a943e-ac2d-46c9-a2c0-ab77e2425bf2,avg product cordlength is small and cooling sy...,15,positive

In [22]:
df["sentiment"].describe()

count         3000
unique           2
top       positive
freq          2432
Name: sentiment, dtype: object

In [23]:
df["sentiment"].count()

np.int64(3000)

In [24]:
df[df["sentiment"] == "negative"].count()

review_uuid      568
review           568
review_length    568
sentiment        568
dtype: int64

In [25]:
df.to_csv("labeled_reviews.csv")